// ==========================================================================
// 📖 课文与字词矩阵数据（按词组单位：全拼音与双语翻译无死角覆盖） - data.js
// ==========================================================================

const lessonTitle = "错位";

const lessonData = [
    // --- 第1段 ---
    ["银座大厦的", "yín zuò dà shà de", "of the Ginza Mansion", "Bangunan Ginza punya"],
    ["底层", "dǐ céng", "ground floor / bottom floor", "tingkat bawah"],
    ["是", "shì", "is", "adalah"],
    ["高档", "gāo dàng", "high-end / upscale", "bermutu tinggi / mewah"],
    ["写字楼。", "xiè zì lóu", "office building", "bangunan pejabat"],
    ["黄昏时分，", "huáng hūn shí fēn", "at dusk / twilight", "pada waktu senja"],
    ["下班的", "xià bān de", "off-work", "yang balik kerja"],
    ["白领们", "bái lǐng men", "white-collar workers", "pekerja kolar putih"],
    ["如潮水般", "rú cháo shuǐ bān", "like a tide", "seperti pasang surut air laut / bagai ombak"],
    ["涌出。", "yǒng chū", "gush out / pour out", "meluru keluar / membanjiri"],
    ["青年", "qīng nián", "youth / young man", "pemuda"],
    ["小彭", "xiǎo péng", "Xiao Peng (name)", "Xiao Peng"],
    ["拖着", "tuō zhe", "dragging", "mengheret / melangkah dengan berat"],
    ["疲惫的", "pí bèi de", "exhausted / tired", "yang letih / lesu"],
    ["步伐", "bù fá", "pace / steps", "langkah kaki"],
    ["走在最后，", "zǒu zài zuì hòu", "walking at the very back", "berjalan di paling belakang"],
    ["他的", "tā de", "his", "dia punya"],
    ["脸色", "liǎn sè", "complexion / facial expression", "riak wajah / muka"],
    ["阴沉得", "yīn chén de", "gloomy / dark", "mendung / muram sehinggakan"],
    ["可怕。", "kě pà", "terrible / scary", "menakutkan"],
    ["就在", "jiù zài", "just / right at", "tepat pada / hanya pada"],
    ["半小时前，", "bàn xiǎo shí qián", "half an hour ago", "setengah jam yang lalu"],
    ["房东", "fáng dōng", "landlord / landlady", "tuan rumah"],
    ["再次", "zài cì", "once again", "sekali lagi"],
    ["发来", "fā lái", "sent over", "mengirimkan"],
    ["最后通牒，", "zuì hòu tōng dié", "ultimatum", "kata dua / amaran terakhir"],
    ["如果", "rú guǒ", "if", "sekiranya / jikalau"],
    ["今晚", "jīn wǎn", "tonight", "malam ini"],
    ["再不", "zài bù", "still not", "masih tidak"],
    ["补齐", "bǔ qí", "make up for / pay the balance", "melunaskan / membayar baki"],
    ["拖欠的", "tuō qiàn de", "overdue / in arrears", "yang tertunggak"],
    ["三个月", "sān gè yuè", "three months", "tiga bulan"],
    ["房租，", "fáng zū", "rent", "sewa rumah"],
    ["明天", "míng tiān", "tomorrow", "esok"],
    ["他的", "tā de", "his", "dia punya"],
    ["行李", "xíng li", "luggage / baggage", "barang-barang / bagasi"],
    ["就会", "jiù huì", "will then", "pun akan"],
    ["被扔到", "bèi rēng dào", "be thrown onto", "dicampak ke"],
    ["大街上。", "dà jiē shàng", "the main street", "atas jalan raya"],
    ["他刚", "tā gāng", "he just", "dia baru sahaja"],
    ["在这个", "zhè gè", "in this", "di... ini"],
    ["城市", "chéng shì", "city", "bandar"],
    ["立足，", "lì zú", "gain a foothold / establish oneself", "bertapak / memulakan hidup"],
    ["高昂的", "gāo áng de", "expensive / high", "yang tinggi / mahal"],
    ["房租", "fáng zū", "rent", "sewa rumah"],
    ["和", "hé", "and", "dan"],
    ["碎银几两的", "suì yín jǐ liǎng de", "a meager amount of silver (low income)", "gaji yang sedikit / kais pagi makan pagi punya"],
    ["工资", "gōng zī", "salary / wages", "gaji / upah"],
    ["压得", "yā de", "press down until", "menekan sehinggakan"],
    ["他", "tā", "he", "dia"],
    ["几乎要", "jī hū yào", "almost / nearly", "hampir-hampir"],
    ["窒息。", "zhì xī", "suffocate / stifle", "lemas / sesak nafas"],
    ["\n", "", "", ""],

    // --- 第2段 ---
    ["大厦", "dà shà", "mansion / large building", "bangunan besar"],
    ["对面的", "duì miàn de", "opposite", "bertentangan / seberang"],
    ["街角，", "jiē jiǎo", "street corner", "penjuru jalan / sudut jalan"],
    ["常年", "cháng nián", "all year round", "sepanjang tahun"],
    ["坐着", "zuò zhe", "sitting", "duduk"],
    ["一个", "yí gè", "a", "seorang"],
    ["卖烤红薯的", "mài kǎo hóng shǔ de", "selling roasted sweet potatoes", "yang menjual ubi keledek bakar"],
    ["老头。", "lǎo tóu", "old man", "orang tua"],
    ["老头", "lǎo tóu", "the old man", "orang tua itu"],
    ["穿着", "chuān zhe", "wearing", "memakai"],
    ["一件", "yí jiàn", "a (classifier for coats/items)", "sehelai"],
    ["泛白", "fàn bái", "faded white / whitish", "pudar warnanya"],
    ["且", "qiě", "and / moreover", "dan juga"],
    ["打着补丁的", "dǎ zhe bǔ dīng de", "patched", "yang bertampal-tampal"],
    ["旧棉袄，", "jiù mián ǎo", "old cotton-padded jacket", "baju sejuk kapas lama"],
    ["脸上", "liǎn shàng", "on the face", "di atas wajah"],
    ["满是", "mǎn shì", "full of", "penuh dengan"],
    ["如刀刻般的", "rú dāo kè bān de", "like deep knife carvings (wrinkles)", "seperti diukir pisau (kedutan dalam)"],
    ["皱纹。", "zhòu wén", "wrinkles", "kedutan"],
    ["在繁华、", "fán huá", "prosperous / bustling", "meriah / pesat / sibuk"],
    ["霓虹闪烁的", "ní hóng shǎn shuò de", "flashing neon lights", "lampu neon yang berkelip-kelip"],
    ["清江", "qīng jiāng", "Qingjiang (city/river name)", "Qingjiang"],
    ["大都市里，", "dà dū shì lǐ", "in the metropolis", "di dalam kota raya besar"],
    ["他", "tā", "he", "dia"],
    ["显得", "xiǎn de", "appeared / looked", "kelihatan"],
    ["那么地", "nà me de", "so / in that way", "sedemikian begitu"],
    ["疏疏落落、", "shū shū luò luò", "scattered / sparse (here: isolated)", "terasing / jarang-jarang"],
    ["格格不入。", "gé gé bú rù", "incompatible / out of place", "janggal / tidak sepadan"],
    ["\n", "", "", ""],

    // --- 第3段 ---
    ["小彭", "xiǎo péng", "Xiao Peng", "Xiao Peng"],
    ["正", "zhèng", "right now", "sedang"],
    ["站在", "zhàn zài", "standing at", "berdiri di"],
    ["路边", "lù biān", "roadside", "tepi jalan"],
    ["焦急地", "jiāo jí dì", "anxiously", "dengan gelisah / cemas"],
    ["等待", "děng dài", "waiting for", "menunggu"],
    ["客户的", "kè hù de", "client's / customer's", "pelanggan punya"],
    ["转账短信，", "zhuǎn zhàng duǎn xìn", "money transfer SMS", "pesanan ringkas (SMS) pindahan wang"],
    ["那故事", "nà", "that", "itu"],
    ["是他", "shì tā", "is his", "ialah dia punya"],
    ["唯一的", "wéi yī de", "only", "satu-satunya"],
    ["救命稻草。", "jiù mìng dào cǎo", "lifesaver / life-saving straw", "talian hayat / jerami penyelamat"],
    ["突然，", "tū rán", "suddenly", "tiba-tiba"],
    ["老头", "lǎo tóu", "the old man", "orang tua itu"],
    ["朝他", "cháo tā", "towards him", "ke arahnya"],
    ["招了招手，", "zhāo le zhāo shǒu", "waved hands", "melambai-lambai tangan"],
    ["有些", "yǒu xiē", "somewhat / a bit", "agak / sedikit"],
    ["嗫嚅、", "niè rú", "mumbling / speak hesitatingly", "ragu-ragu / teragap-agap (bercakap)"],
    ["怯懦地", "qiè nuò dì", "timidly / cowardly", "dengan segan / penakut"],
    ["开口：", "kāi kǒu", "open mouth to speak", "membuka mulut bercakap:"],
    ["“年轻人，", "qīng nián rén", "young man", "orang muda / pemuda"],
    ["能借你的", "néng jiè nǐ de", "can borrow your", "boleh pinjam kamu punya"],
    ["手机", "shǒu jī", "mobile phone", "telefon bimbit"],
    ["用一下吗？", "yòng yí xià ma", "use for a moment?", "guna sekejap?"],
    ["我想给", "wǒ xiǎng gěi", "I want to to", "saya mahu telefon kepada"],
    ["乡下的", "xiāng xià de", "countryside / rural", "kampung punya"],
    ["孙子", "sūn zi", "grandson", "cucu lelaki"],
    ["拨个电话，", "bō diàn huà", "make a phone call", "membuat panggilan telefon"],
    ["我的", "tā de", "my", "saya punya"],
    ["旧机器", "jiù jī qì", "old machine (old phone)", "telefon lama / mesin tua"],
    ["没电了……”", "méi diàn le", "out of battery", "kehabisan bateri / kuasai..."],
    ["\n", "", "", ""],

    // --- 第4段 ---
    ["小彭", "xiǎo péng", "Xiao Peng", "Xiao Peng"],
    ["心里", "xīn lǐ", "in the heart", "di dalam hati"],
    ["猛地一紧，", "měng de yì jǐn", "heart suddenly tightened", "jantung tiba-tiba sentak sebak"],
    ["所有的", "suǒ yǒu de", "all the", "kesemua"],
    ["惊讶、", "jīng yà", "surprise / astonishment", "perasaan terkejut"],
    ["警惕", "jǐng tì", "vigilance / alertness", "sikap waspada / berhati-hati"],
    ["与", "yǔ", "and", "dan"],
    ["鄙夷", "bǐ yí", "disdain / contempt", "pandangan hina / jijik"],
    ["渐渐", "jiàn jiàn", "gradually", "beransur-ansur / perlahan-lahan"],
    ["涌上心头。", "yǒng shàng xīn tóu", "welled up in the heart", "meluap ke hulu hati."],
    ["在这个", "zhè gè", "in this", "di... ini"],
    ["各顾各的", "gè gù gè de", "each minding his own business", "masing-masing jaga diri sendiri punya"],
    ["城市里，", "chéng shì lǐ", "city", "bandar"],
    ["他看多了", "tā kàn duō le", "he saw a lot of", "dia sudah banyak melihat"],
    ["骗子的", "piàn zi de", "swindler's / scammer's", "penipu punya"],
    ["套路。", "tào lù", "routines / tricks / traps", "taktik / helah / perangkap"],
    ["他", "tā", "he", "dia"],
    ["目瞪口呆地", "mù dèng kǒu dāi dì", "dumbfounded / gaped in shock", "tercengang / melongo lidah"],
    ["看着", "kàn zhe", "looking at", "memandang"],
    ["老头", "lǎo tóu", "the old man", "orang tua itu punya"],
    ["那双", "nà shuāng", "that pair of", "sepasang"],
    ["沾满黑灰、", "zhān mǎn hēi huī", "covered with black ash", "yang diselubungi abu hitam / arang"],
    ["长满老茧的", "zhǎng mǎn lǎo jiǎn de", "calloused", "yang penuh dengan kapal / kematu"],
    ["手，", "shǒu", "hand", "tangan"],
    ["心想：", "xīn xiǎng", "thinking in mind", "berfikir dalam hati:"],
    ["这老头", "zhè lǎo tài", "this old man", "orang tua ini"],
    ["难道是", "nán dào shì", "could it be (rhetorical)", "takkan sememangnya"],
    ["别有用心？", "bié yǒu yòng xīn", "have ulterior motives", "mempunyai agenda tersembunyi?"],
    ["想借机", "xiǎng jiè jī", "want to take the chance to", "mahu mengambil kesempatan untuk"],
    ["抢走", "qiǎng zǒu", "snatch away / rob", "meragut / merampas pergi"],
    ["我新买的", "wǒ xīn mǎi de", "my newly bought", "saya baru beli punya"],
    ["手机？", "shǒu jī", "phone?", "telefon?"],
    ["还是", "hái shi", "or", "atau"],
    ["想打", "xiǎng dǎ", "want to make", "mahu membuat"],
    ["跨国", "kuà guó", "transnational / international", "antarabangsa"],
    ["诈骗电话？", "zhà piàn diàn huà", "fraud phone call / scam call", "panggilan telefon penipuan?"],
    ["\n", "", "", ""],

    // --- 第5段 ---
    ["可是，", "kě sài", "however / but", "tetapi / namun"],
    ["看到", "kàn dào", "seeing", "melihat"],
    ["老头", "lǎo tóu", "the old man", "orang tua itu punya"],
    ["那双", "nà shuāng", "that pair of", "sepasang"],
    ["凹陷下去的", "āo xiàn xià qù de", "sunken / hollowed", "yang cengkung / terperosok ke dalam"],
    ["眼睛里", "yǎn jing zhōng", "inside the eyes", "mata di dalam"],
    ["闪动着", "shǎn dòng zhe", "flickering with", "memancarkan / berkelip"],
    ["某种", "mǒu zhǒng", "some kind of", "suatu / sejenis"],
    ["卑微的", "bēi wēi de", "humble / petty / low status", "rendah diri / kerdil / hina"],
    ["乞求，", "qǐ qiú", "pleading / begging", "rayuan / permohonan"],
    ["小彭", "xiǎo péng", "Xiao Peng", "Xiao Peng"],
    ["按捺不住", "àn nà bú zhù", "cannot control oneself / hold back", "tidak dapat menahan sabar / membendung"],
    ["长叹了一口气。", "cháng tàn le yì kǒu qì", "heaved a long sigh", "mengeluh panjang sepatah."],
    ["他", "tā", "he", "dia"],
    ["打定", "dǎ dìng", "make up one's mind", "menetapkan hati"],
    ["不到黄河心不死", "bú dào huáng hé xīn bù sǐ", "not stop until reaching the limit / completely determined", "tidak akan menyerah kalah selagi belum sampai ke penghujungnya"],
    ["的主意，", "de zhǔ yi", "idea / decision", "keputusan / tekad"],
    ["极不情愿地", "jí bù qíng yuàn dì", "extremely reluctantly", "dengan amat tidak rela / terpaksa"],
    ["把手机", "bǎ shǒu jī", "take the phone (object marker)", "telefon bimbit (penanda objek)"],
    ["递了过去，", "dì le guò qù", "handed over", "menyerahkan ke sana"],
    ["但", "dàn", "but", "tetapi"],
    ["脚步", "bù fá", "footsteps / steps", "langkah kaki"],
    ["却", "què", "however", "namun"],
    ["死死地", "sǐ sǐ dì", "deadly / rigidly / stubbornly", "tegar-tegar / melekat rapat"],
    ["挪在", "nuó zài", "moved next to", "beralih di sebelah"],
    ["老头身边，", "lǎo tóu shān biān", "beside the old man", "orang tua itu"],
    ["多双眼睛，", "duō shuāng yǎn jing", "an extra pair of eyes", "sepasang mata lagi"],
    ["会少些", "huì shǎo xiē", "will reduce / avoid", "akan mengurangkan sikit"],
    ["不必要的", "bú bì yào de", "unnecessary", "yang tidak perlu"],
    ["损失。", "sǔn shī", "loss / damage", "kerugian."],
    ["他", "tā", "he", "dia"],
    ["像贼一样地", "zé yí yàng dì", "like a thief", "seperti seorang pencuri"],
    ["死死盯着", "sǐ sǐ dīng zhe", "staring intently at", "merenung tajam pada"],
    ["老头的", "lǎo tóu de", "old man's", "orang tua itu punya"],
    ["每一个动作，", "měi gè dòng zuò", "every single movement", "setiap satu perbuatan"],
    ["随时", "suí shí", "at any time", "pada bila-bila masa sahaja"],
    ["准备", "zhǔn bèi", "ready to / prepare", "bersedia"],
    ["在老头", "zài lǎo tóu", "when the old man", "apabila orang tua"],
    ["妄动时", "wàng dòng shí", "act recklessly / run away", "bertindak liar / mencuri"],
    ["夺回", "duó huí", "snatch back / reclaim", "merampas semula"],
    ["手机。", "shǒu jī", "phone.", "telefon."],
    ["\n", "", "", ""],

    // --- 第6段 ---
    ["老头", "lǎo tóu", "the old man", "orang tua itu"],
    ["似乎", "sì hū", "seemingly / as if", "nampaknya / seolah-olah"],
    ["觉察到了", "jué chá dào le", "noticed / perceived", "menyedari / mengesan"],
    ["这双", "zhè shuāng", "this pair of", "sepasang... ini"],
    ["充满防备的", "chōng mǎn fáng bèi de", "full of defensiveness / guarded", "yang penuh dengan sikap berhati-hati"],
    ["眼睛，", "yǎn jing", "eyes", "mata"],
    ["他", "tā", "he", "dia"],
    ["有些", "yǒu xiē", "somewhat / a bit", "agak / sedikit"],
    ["局促地", "jú cù dì", "constrainedly / awkwardly / uneasily", "dengan canggung / gelisah"],
    ["笑了笑，", "xiào le xiào", "smiled", "tersenyum sedikit"],
    ["粗大的", "cū dà de", "thick and large / coarse", "yang kasar dan besar"],
    ["手指", "shǒu zhǐ", "fingers", "jari-jemari"],
    ["笨拙地", "bèn zhuō dì", "clumsily / awkwardly", "dengan gopoh / kekok"],
    ["在屏幕上", "zài píng mù shàng", "on the screen", "di atas skrin"],
    ["按着。", "àn zhe", "pressing", "menekan."],
    ["电话", "diàn huà", "phone call", "panggilan telefon"],
    ["很快", "hěn kuài", "very quickly", "dengan cepat"],
    ["通了，", "tōng le", "connected / got through", "disambungkan"],
    ["老头", "lǎo tóu", "the old man", "orang tua itu"],
    ["用极其", "yòng jí qí", "using extremely", "dengan menggunakan amat"],
    ["亲昵、", "qīn nì", "affectionate / intimate", "mesra / penuh kasih sayang"],
    ["热烈的", "rè liè de", "warm / enthusiastic", "hangat / rancak"],
    ["口气", "kǒu qì", "tone of voice", "nada suara"],
    ["喊着：", "hǎn zhe", "calling out", "memanggil-manggil:"],
    ["“捷儿、", "jié ér", "Jie er (grandson's name)", "Jie er"],
    ["捷儿，", "jié ér", "Jie er", "Jie er"],
    ["外婆", "wài pó", "maternal grandmother", "nenek"],
    ["和你爸", "hé nǐ bà", "and your dad", "dan ayah kamu"],
    ["都", "dōu", "all", "kesemuanya"],
    ["挺好的，", "tǐng hǎo de", "very well / doing fine", "sangat baik"],
    ["地里的", "dì lǐ de", "in the fields", "ladang / tanah punya"],
    ["庄稼", "zhuāng jia", "crops", "tanaman / hasil bumi"],
    ["收成好，", "shōu cheng hǎo", "good harvest", "menjadi hasilnya / menuai baik"],
    ["黄土变成了金……", "huáng tǔ biàn chéng jīn", "dirt turns to gold (good fortune)", "tanah pun menjadi emas..."],
    ["你安心", "nǐ ān xīn", "you at peace / peacefully", "kamu dengan tenang"],
    ["在外面", "zài wài miàn", "outside / abroad", "di luar sana"],
    ["读书，", "dú shū", "studying / studying hard", "belajar / menuntut ilmu"],
    ["别省钱，", "bié shěng qián", "don't scrimp on money / don't save too much", "jangan kedekut wang / jimat sangat"],
    ["爷爷", "yé ye", "grandfather", "datuk"],
    ["这里", "zhè lǐ", "here", "di sini"],
    ["有闲钱", "yǒu xián qián", "have spare money", "ada wang lebih"],
    ["呢……”", "ne", "(particle)", "lah..."],
    ["\n", "", "", ""],

    // --- 第7段 ---
    ["听到", "tīng dào", "hearing", "mendengar"],
    ["这番", "zhè fān", "this speech / this kind of", "perbualan ini"],
    ["对话，", "duì huà", "dialogue / conversation", "perbualan / dialog"],
    ["小彭的", "xiǎo péng de", "Xiao Peng's", "Xiao Peng punya"],
    ["心", "xīn", "heart", "jantung / hati"],
    ["就像", "jiù xiàng", "just like", "seolah-olah"],
    ["发生了", "fā shēng le", "occurred", "berlaku"],
    ["强烈的", "qiáng liè de", "intense / strong", "hebat / kuat"],
    ["地震", "dì zhèn", "earthquake", "gempa bumi"],
    ["一般，", "yī bān", "as if / like", "sedemikian"],
    ["久久", "jiǔ jiǔ", "for a long time", "lama sekali"],
    ["无法", "wú fǎ", "unable to / cannot", "tidak mampu / tidak boleh"],
    ["平静。", "píng jìng", "calm down", "berasa tenang semula."],
    ["老头", "lǎo tóu", "the old man", "orang tua itu"],
    ["只说了", "zhǐ shuō le", "only spoke for", "hanya bercakap selama"],
    ["一分钟，", "yì fēn zhōng", "one minute", "seminit"],
    ["便", "biàn", "then / so", "lalu / maka"],
    ["千恩万谢地", "qiān ēn wàn xiè dì", "with thousand thanks", "dengan ucapan beribu-ribu terima kasih"],
    ["把手机", "bǎ shǒu jī", "the phone (object marker)", "telefon bimbit (penanda objek)"],
    ["还给了", "huán gěi le", "returned to", "memulangkan kepada"],
    ["小彭，", "xiǎo péng", "Xiao Peng", "Xiao Peng"],
    ["并", "bìng", "and", "serta"],
    ["执意", "zhí yì", "insist on / obstinately determined", "berkeras / berteguh hati"],
    ["从怀里", "cóng huái lǐ", "from the bosom", "daripada dalam dada / baju"],
    ["掏出", "tāo chū", "took out", "mengeluarkan"],
    ["一块", "yí kuài", "a piece of", "sekeping"],
    ["热腾腾、", "rè téng téng de", "piping hot", "yang panas berasap"],
    ["黄亮如金的", "huáng liàng rú jīn de", "bright yellow like gold", "kuning berkilat bagai emas"],
    ["烤红薯", "kǎo hóng shǔ", "roasted sweet potato", "ubi keledek bakar"],
    ["往小彭", "wǎng xiǎo péng", "towards Xiao Peng", "ke arah Xiao Peng punya"],
    ["手里塞：", "shǒu lǐ sāi", "stuffing into the hand", "tangan disumbatkan:"],
    ["“年轻人，", "qīng nián rén", "young man", "orang muda / pemuda"],
    ["谢谢你，", "xiè xie nǐ", "thank you", "terima kasih kepadamu"],
    ["你是个", "nǐ shì gè", "you are a", "kamu merupakan seorang"],
    ["好人。”", "hǎo rén", "good person.", "orang baik."],
    ["\n", "", "", ""],

    // --- 第8段 ---
    ["就在这时，", "jiù zài zhè shí", "right at this moment", "tepat pada waktu ini"],
    ["小彭的", "xiǎo péng de", "Xiao Peng's", "Xiao Peng punya"],
    ["手机", "shǒu jī", "phone", "telefon"],
    ["叮咚一响，", "dīng dōng yì xiǎng", "ding-dong chimed", "berbunyi ding-dong sepatah"],
    ["房东的", "fáng dōng de", "landlord's", "tuan rumah punya"],
    ["催租微信", "cuī zū wēi xìn", "rent-collecting WeChat message", "pesanan WeChat menuntut sewa"],
    ["再次", "zài cì", "once again", "sekali lagi"],
    ["弹出来。", "tán chū lái", "popped up / bounced out", "terkeluar / meloncat keluar."],
    ["看着", "kàn zhe", "looking at", "memandang"],
    ["手中", "shǒu zhōng", "in the hand", "di dalam tangan"],
    ["那块", "nà kuài", "that piece of", "sekeping... itu"],
    ["散发着", "sàn fā zhe", "emitting / sending out", "mengeluarkan / memancarkan haruman"],
    ["暗香、", "àn xiāng", "subtle fragrance", "haruman yang lembut"],
    ["捂热了", "wǔ rè le", "warmed up", "memanaskan / menghangatkan"],
    ["他冰冷双手的", "tā bīng lěng shuāng shǒu de", "his icy cold hands", "dia punya sepasang tangan yang sejuk beku"],
    ["红薯，", "hóng shǔ", "sweet potato", "ubi keledek"],
    ["再看看", "zài kàn kàn", "looking again at", "melihat sekali lagi ke arah"],
    ["老头", "lǎo tóu", "the old man", "orang tua itu punya"],
    ["那满足、", "mǎn zú", "satisfied", "kepuasan"],
    ["豁达的", "huò dá de", "open-minded / optimistic", "berlapang dada / fikiran terbuka"],
    ["笑容，", "xiào róng", "smile", "senyuman"],
    ["两行", "liǎng háng", "two lines", "dua titisan"],
    ["温热的泪水", "wēn rè de lèi shuǐ", "warm tears", "air mata yang hangat"],
    ["却", "què", "but", "namun"],
    ["无声无息地", "wú shēng wú xī dì", "silently / without a sound", "tanpa sebarang bunyi"],
    ["从主角", "cóng zhǔ jué", "from the protagonist's", "daripada watak utama punya"],
    ["脸上", "liǎn shàng", "face", "wajah"],
    ["淌下来。", "tǎng xià lái", "streamed down.", "mengalir turun."],
    ["\n", "", "", ""],

    // --- 第9段 ---
    ["真正", "zhēn zhèng", "truly / genuinely", "hakikatnya sememangnya"],
    ["错位的，", "cuò wèi de", "misplaced / dislocated", "berganjak kedudukannya / salah tempat"],
    ["哪里是", "nǎ lǐ shì", "how can it be (rhetorical)", "mana boleh dikatakan adalah"],
    ["老太太", "lǎo tài tai", "old lady", "wanita tua"],
    ["或", "huò", "or", "atau"],
    ["底层人的", "dǐ céng rén de", "bottom-class people's / grassroots'", "golongan bawah punya"],
    ["衣着打扮，", "yī zhuó dǎ bàn", "clothing and attire", "pakaian dan gaya hiasan"],
    ["而是", "ér shì", "but rather", "tetapi melainkan"],
    ["这都市里", "zhè dū shì lǐ", "in this city", "di dalam kota raya ini"],
    ["被物欲", "bèi wù yù", "by material desires", "oleh nafsu kebendaan / materialistik"],
    ["和", "hé", "and", "dan"],
    ["警惕", "jǐng tì", "vigilance / suspicion", "sikap berwaspada / menaruh curiga"],
    ["填满的、", "tián mǎn de", "filled up", "dipenuhi"],
    ["变得", "biàn de", "became", "menjadi"],
    ["不再", "bú zài", "no longer", "tidak lagi"],
    ["纯洁的", "chún jié de", "pure", "suci / bersih punya"],
    ["玲珑心啊。", "líng lóng xīn", "exquisite and fragile heart", "hati yang rapuh / licik."],
    ["\n", "", "", ""],

    // --- 作者落款 ---
    ["（刘心武《错位》，有改动）", "", "", ""]
];
